New resampling
LASY-org/lasy pull request #269
Opened 2024-07-18 11:52 UTC by NadezhdaKHACHAT

Copy of a #202 PR but the library is mostly up to date. Added an automated test for the resampling feature.

Adds the option to resample the field onto a new grid during the propagation step. This can be useful for example when focusing the laser from a large beam size to a small spot.

The resampling option only works in the 'rt' geometry. In order to resample the fields, the user can pass a new grid object (changing the radial size of the grid but not the resolution) to the propagate() function. The new grid replaces the original grid.

2024-07-22 16:37 UTC, RemiLehe commented
@NadezhdaKHACHAT Thanks a lot for this PR!
Would you be able to fix the `git` conflicts here?

2024-07-23 11:12 UTC, RemiLehe commented on tests/test_resampling.py
> +    new_grid = Grid(dim, lo, (new_r_max, hi[1]), npoints, n_azimuthal_modes=laser.grid.n_azimuthal_modes)
`laser.grid.n_azimuthal_modes` is not defined at this point, which causes this test to fail for now.

2024-08-06 20:22 UTC, RemiLehe commented on lasy/laser.py
> +
```suggestion
```

2024-08-21 16:47 UTC, RemiLehe commented on lasy/laser.py
> +            of raidal grid points. Only works for ``'rt'``.
```suggestion
            of radial grid points. Only works for ``'rt'``.
```

2024-08-21 16:53 UTC, RemiLehe commented on lasy/laser.py
> +                    spectral_field = spectral_field_n
Could this be simplified to:
```suggestion
                    spectral_field[i_m, :, :] = np.transpose(transform_data).copy()
```

2024-08-21 16:58 UTC, RemiLehe commented on lasy/laser.py
> +                    del self.prop
This needs to be outside of the loop 
```
for i_m in range(self.grid.azimuthal_modes.size):
```
correct?

2024-08-21 17:00 UTC, RemiLehe commented on tests/test_resampling.py
> +the focal position (radial axis is resampled to accomodate the new size of the beam) ; we then check that the waist as the
```suggestion
the focal position (radial axis is resampled to accomodate the new size of the beam) ; we then check that the waist has the
```

2024-08-21 17:01 UTC, RemiLehe requested changes
Thanks for this PR.

I noticed a potential bug, I think, in the case where several azimuthal modes are present. Could you include a case with multiple azimuthal modes (e.g. Laguerre-Gauss pulse focused by a parabolic mirror) in the automated test?

2024-08-27 21:22 UTC, rob-shalloo commented
Hey, this is a really great PR! Thanks @NadezhdaKHACHAT! I've been testing it out recently and one question is whether we should include some information in the doc string relating to the resolution and range of both grids and how they should relate to the propagation distance. As an example, if you take your test case and just change the focal length to 0.5 m (not crazy for a 5 mm beam), the numerical calculation no longer matches the theory prediction. 
Another option is to include some kind of helper function to flag when the chosen parameters are unlikely provide physical results. I think Igor did this in the original propagator (see `def check_new_grid(self, dz):`)

2024-09-02 14:37 UTC, RemiLehe commented
It looks like the option `overwrite=False` is causing issues.

For instance, the test `test_gaussian_propagator.py` is currently broken, whereas it should not be affected by this PR.

When changing:
```python
                transform_data = self.prop[i_m].step(
                    transform_data,
                    distance,
                    overwrite=False,
                    show_progress=show_progress,
                )
```
to 
```
                self.prop[i_m].step(
                    transform_data,
                    distance,
                    overwrite=True,
                    show_progress=show_progress,
                )
```
This test passes again.

2024-09-02 14:49 UTC, RemiLehe commented
It seems that the above-mentioned issue is fixed by this `axiprop` commit:
https://github.com/hightower8083/axiprop/commit/25d58eaf37941bba1274ad2011f1760fc8534fb1
which is not included in the latest PyPI release.

2024-09-03 15:28 UTC, RemiLehe approved these changes

2024-09-03 15:30 UTC, merged