[WIP] Enable initialisation of optional spatio-temperal coupling parameters to gaussian profile
LASY-org/lasy pull request #307
Opened 2024-10-15 19:19 UTC by huixingjian

### PR Description
This PR enables initialisation of first-order spatio-temperal  coupling parameters in Gaussianprofile.  Four additional parameters are added to the constructor of ''' GaussianLongitudinalProfile''', namely, group-delay dispersion '''phi2''' in $s^2$ parameterized by $\phi^{(2)} = \frac{dt}{d\omega}$, spatio-chirp '''zeta''' in $m\cdot s$parameterized by $\zeta = \frac{x_0}{d\omega}$(Here $x_0$ is the beam center position), and  angular dispersion in $s$  parameterized by $\beta = \frac{d\theta_0}{d\omega}$( Here $\theta_0$ is the propagation angle of this component.)
### Issue addressed

### Benefits

### Important Note

### Test

2024-12-11 20:06 UTC, MaxThevenet requested changes
Thanks for this PR! Very nice that you can have all sorts of chirps together and can disentangle them in post-processing. See comments below, mostly about cleaning and clarifying.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/profiles/gaussian_profile.py
> +    beta : float (in second), optional
```suggestion
    beta : float (in second), optional (default '0')
```

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/profiles/gaussian_profile.py
> +        The spatio-chirp parameterized by:
```suggestion
        The spatial chirp, parameterized by:
```

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/profiles/gaussian_profile.py
> +        Transverse direction along which spatio-temporal field couples.
```suggestion
        Transverse direction along which there are chirps and spatio-temporal couplings.
```

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/profiles/longitudinal/gaussian_profile.py
This profile should not be changed, or just marginally. This implementation should be in `profiles/gaussian_profile.py`.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/profiles/longitudinal/longitudinal_profile.py
This profile should not be changed.

2024-12-11 20:06 UTC, MaxThevenet commented on tests/test_STC.py
> +    stc_theta=scc.pi / 2,
Could you make the style consistent?

2024-12-11 20:06 UTC, MaxThevenet commented on tests/test_STC.py
> +    hi=(10e-6, +10e-14),
style consistency

2024-12-11 20:06 UTC, MaxThevenet commented on tests/test_STC.py
> +np.testing.assert_approx_equal(STC_3d["zeta_y"], 2.4e-24, significant=2)
Any reason to use this over `np.isclose`? We us that one in some place.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +        that defines the points at which the laser is defined.
I would recommend to write 1 sentence per line. The pre-commit CI will fix it.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    # Initialise the returned dictionary
US English was used above, and is the norm in LASY.
```suggestion
    # Initialize the returned dictionary
```

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    env_abs = np.abs(env**2)
Could you make the naming more accurate?

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +            zeta_x, zeta_y: Spatio-chirp in :math:`\zeta=dx_0/d(\omega_0)`
Group Delay Dispersion (GDD) and spatial chirp.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    omega = 2 * np.pi * np.fft.fftfreq(Nt, dt) + k0 * c
Ok, indeed this axis doesn't seem to be available from Grid. I think this should be fixed, good point!

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    phi_envelop = np.unwrap(np.array(np.arctan2(env.imag, env.real)), axis=2)
1D unwrapping can be a bit dodgy. Also, `np.angle` would be nicer here.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +        np.roots([4 * STC_fac["Phi2"], -4, tau**4 * STC_fac["Phi2"]])
always the right value?

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +def get_STC(dim, grid, k0):
I think we should cut this into multiple functions, with clear names, and put the commonalities in helper functions.

2024-12-11 20:06 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    # No spatial chirp and angular chirp in 'rt' coordinate
Overall everything below would benefit from more comments, to gain clarity.

2024-12-11 21:01 UTC, MaxThevenet commented
Please check in particular https://github.com/LASY-org/lasy/pull/182/files#r1406449309

2024-12-19 14:02 UTC, MaxThevenet requested changes
Thanks! Please see comments

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/profiles/longitudinal/longitudinal_profile.py
> +        self.k0 = 2.0 * pi / wavelength
I don't think it's used anywhere.
```suggestion
```

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    phi_envelop = np.unwrap(np.array(np.arctan2(env.imag, env.real)), axis=2)
`np.angle`?
Note that this 1D unwrapping is very easily very wrong. But if that's a problem we could implement a 3D unwrapping later one, there was an example of this actually in LASY at some point.

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    Calculate the spatio-chirp of the laser.
```suggestion
    Calculate the spatial chirp of the laser.
```

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    zeta_x, zeta_y: Spatio-chirp in :math:`\zeta=dx_0/d(\omega_0)` (meter * second)
```suggestion
    zeta_x, zeta_y: Spatial chirp in :math:`\zeta=dx_0/d(\omega_0)` (meter * second)
```

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    nu_x, nu_y: Spatio-chirp in :math:`\nu=d(\omega_0)/dx` (meter^-1 * second^-1)
Also, please fix space before colon for parameters everywhere!
```suggestion
    nu_x, nu_y : Spatial chirp in :math:`\nu=d(\omega_0)/dx` (meter^-1 * second^-1)
```

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    assert dim == "xyt", "No spatial chirp for axis-sysmetric dimension"
!

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    beta_x, beta_y: Angular dispersion in :math:` \beta = d\theta_0/d\omega` (second)
```suggestion
    beta_x, beta_y : Angular dispersion in :math:` \beta = d\theta_0/d\omega` (second)
```
and everywhere

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    Calculate the pulse-front-tilt dispersion of the laser.
```suggestion
    Calculate the pulse front tilt (PFT) of the laser.
```

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    pft_x, pft_y: Pulse front tilt in :math:` p=dt/dx` (second * meter^-1)
```suggestion
    pft_x, pft_y : Pulse front tilt in :math:` p=dt/dx` (second * meter^-1)
```

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    assert dim == "xyt", "No pulse front tilt for axis-sysmetric dimension"
Please fix all

2024-12-19 14:02 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    angle_x, angle_y: propagating angle in :math:` p=k_x or k_y/kz` (rad)
```suggestion
    angle_x, angle_y : propagating angle in :math:` p=k_x or k_y/kz` (rad)
```
please fix all

2024-12-19 15:41 UTC, MaxThevenet reviewed
Looks fantastic! Just minor comments.

2024-12-19 15:41 UTC, MaxThevenet commented on lasy/profiles/gaussian_profile.py
> +        x,y : ndarrays of floats, necessray if spatio-temperal coulping exists
```suggestion
        x,y : ndarrays of floats, necessary if spatio-temporal coupling exists
```

2024-12-19 15:41 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    ----------
```suggestion
    Returns
    -------
```

2024-12-19 15:41 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    pft_x, pft_y : Pulse front tilt in :math:` p=\frac{dt_0}{dx}` (second * meter^-1).
```suggestion
    pft_x, pft_y : Pulse front tilt in :math:`p=\frac{dt_0}{dx}` (second * meter^-1).
```

2024-12-19 15:41 UTC, MaxThevenet commented on lasy/utils/laser_utils.py
> +    assert dim == "xyt", "No pulse front tilt for axis-symmetric dimension."
```suggestion
    assert dim == "xyt", "No pulse front tilt for cylindrical symmetry."
```

2024-12-19 15:51 UTC, MaxThevenet commented on lasy/profiles/gaussian_profile.py
> +        The group-delay dispersion defined as :math:`\phi^{(2)} = \frac{dt_0}{d\omega}. Here :math:`t_0` is the temporal position of this frequency component.
```suggestion
        The group-delay dispersion defined as :math:`\phi^{(2)} = \frac{dt_0}{d\omega}`. Here :math:`t_0` is the temporal position of this frequency component.
```

2024-12-19 15:51 UTC, MaxThevenet commented on lasy/profiles/gaussian_profile.py
> +        A spatial chirp defined as: math:`\zeta = \frac{dx_0}{d\omega}`. Here :math:`x_0` is the transverse beam center position of this frequency component.
```suggestion
        A spatial chirp defined as :math:`\zeta = \frac{dx_0}{d\omega}`. Here :math:`x_0` is the transverse beam center position of this frequency component.
```

2024-12-19 15:55 UTC, MaxThevenet approved these changes
\o/

2024-12-19 15:55 UTC, merged

2025-02-28 19:00 UTC, spencerjolly commented
Nice work!