[WIP] Utility to denoise laser profile
LASY-org/lasy pull request #315
Opened 2024-10-23 22:13 UTC by Paaaaarth

2024-10-25 04:47 UTC, MaxThevenet requested changes
Thanks for this PR! A few general points:
1. Good idea to put this in a separate file `denoise.py` as you propose, if we consider having other denoising methods implemented later. Could you adapt the naming etc.? For instance, the function could be called: `denoise_LG_modes` or so.
2. I would encourage you to check [`mode_decomposition.py`](https://github.com/LASY-org/lasy/blob/development/lasy/utils/mode_decomposition.py), it can take either a full Laser profile or a Transverse profile, and explain what it does in each case. IMO the clearest would be for your function to take a generic `profile` that can be a `TransverseProfile` or a `Laser` but always return a `TransverseProfile`. In the future, we could always return the same type as input, I think that would be the best, but would take more work to handle the longitudinal data.
3. Could you avoid ambiguous input arguments like `parameters` bundling different variables, unless necessary? Just pass the arguments you need, and no more (for instance you may get rid of `polarization`).
4. Please document all input parameters, check other functions for example.
5. Please add a CI test.

2024-11-22 14:33 UTC, Paaaaarth commented
With D4, We have added the additional capability of inputing an image file as transverse profile.

2024-12-11 20:41 UTC, rob-shalloo commented
Hey @Paaaaarth thanks for the PR! This is great to have the functionality in one place. I would make a few suggestions. Feel free to take or leave as you see fit.

1) While this is a great technique to denoise laser profiles, I actually think this goes much beyond just denoising. We're really talking here about creating an analytic representation of the laser pulse (as a sum of HG modes) from an arbitrary input profile. I would then suggest that you change the name to something like `hg_reconstruction`. We could of course collect such methods as Maxence suggest like `lg_reconstruction` in one place within the documentation to showcase their use for denoising.

2) I would suggest removing the creation of a `transverse_profile_from_data` here and leave that to the user. Ie have an assert that you only accept existing transverse profiles or again as Maxence suggest full laser profiles could be interesting in the future. I think the `transverse_profile_from_data` complicates things as it would not be so generic. You in any case do not allow the user to select how the raw image is processed, for example, the threshold at which you set pixel values to 0 (here it appears to be anything less than 1%). This always takes some tuning depending on the camera model, bit depth, background subtraction, signal strength etc.

3) This is probably a larger 'fix' but I would also suggest we allow different values of the waist in `x` and `y` and actually that in addition to providing some functionality to "guess" the values, we allow the user to specify values. A sensible choice of waist can quite often speed up the decomposition / reconstruction process. This would mean digging into `hermite_gauss_decomposition` a bit.

2024-12-11 20:58 UTC, MaxThevenet requested changes
Thanks for this PR! The core of it looks good, see some comments below.
As per Rob's points:
1. the naming: sounds good to me, I don't do denoising etc. on a daily basis.
2. agreed, I think I have a similar comment in a comment below.
3. Indeed the option of having 2 waists would be nice. Can be done in a follow-up PR.

2024-12-11 20:58 UTC, MaxThevenet commented on lasy/utils/denoise.py
> +    transverse_profile : class instance
```suggestion
    transverse_profile : TransverseProfile object
```

2024-12-11 20:58 UTC, MaxThevenet commented on lasy/utils/denoise.py
> +        a path to an image file from which intensity data will be read.
Let avoid ambiguity in the input parameter: it has one type, simple. In order to read an image, the user would create their own `TransverseProfileFromData` and pass it there ok?
```suggestion
        An instance of a class or sub-class of TransverseProfile.
```

2024-12-11 20:58 UTC, MaxThevenet commented on lasy/utils/denoise.py
> +        during the decomposition calculation.
```suggestion
        The number of grid points in x and y used during the decomposition calculation.
```

2024-12-11 20:58 UTC, MaxThevenet commented on lasy/utils/denoise.py
> +        decomposition will be performed.
Overall I personally would have a preference for present tense all over (there are some more instances below).
```suggestion
        decomposition is be performed.
```

2024-12-11 20:58 UTC, MaxThevenet commented on lasy/utils/denoise.py
> +    resolution : float
Please specify here too when a parameter is optional. Also true for others below.

2024-12-11 20:58 UTC, MaxThevenet commented on lasy/utils/denoise.py
> +    n_modes_y=2,
I think only `n_modes_x/y` should be optional, and given a meaningful value, e.g., 10. For the others, the user will get something likely wrong and confusing with default values.

2025-02-05 15:31 UTC, MaxThevenet requested changes
Looks great! See 1 comment below.

2025-02-05 15:31 UTC, MaxThevenet commented on tests/test_denoise.py
> +    assert 0 < np.max(error) < 0.2
This condition is IMO a bit weak. Could you make it a bit stronger? A different norm as used below (code not tested) would be preferable.
```suggestion
    prof1 = transverse_profile.evaluate(X, Y)
    prof2 = transverse_profile_cleaned.evaluate(X, Y)
    error = np.sum(np.abs(prof2-prof1)**2) / np.sum(np.abs(prof1)**2)
    assert error < 0.01 # or something
```

2025-02-06 16:32 UTC, MaxThevenet commented
Could you address the comment before requesting another review?

2025-02-07 13:54 UTC, Paaaaarth commented
> Could you address the comment before requesting another review?

Requested change has been implemented:)

2025-02-07 14:00 UTC, MaxThevenet approved these changes
Looks great, thanks!

2025-02-07 14:00 UTC, merged