[WIP] Updating Definition of Laguerre-Gaussian Modes
LASY-org/lasy pull request #321
Opened 2024-11-12 12:10 UTC by em-archer

Here we provide an update to the Laguerre-Gaussian Transverse Profile to bring the definition in line with that of Siegman (Lasers, 1986), this is analogous to PR #319 for the Hermite-Gaussians.

These changes include correcting the phase terms and improved notation and citations where further information can be found. Additionally, an example is provided for execution within the doc string to plot the modes, rather than a hard linked picture in the documentation.

2024-11-25 07:15 UTC, em-archer commented
Just a note to say that I also updated the docs here as per PR #327 from @Paaaaarth

2024-11-26 19:14 UTC, MaxThevenet requested changes
Thanks for this PR! See minor comments below, just a few typos.
The example in laguerre_gaussian_profile.py is really cool and renders great in the doc! https://lasydoc--321.org.readthedocs.build/en/321/api/profiles/transverse/laguerre_gaussian_profile.html

2024-11-26 19:14 UTC, MaxThevenet commented on lasy/profiles/transverse/laguerre_gaussian_profile.py
> +        \Phi(z) = \left(2 p + m + 1\right) \tan^{-1}\left({\frac{z}{Z_R}}\right)
Just to avoid confusion between cotan and arctan
```suggestion
        \Phi(z) = \left(2 p + m + 1\right) \arctan\left({\frac{z}{Z_R}}\right)
```

2024-11-26 19:14 UTC, MaxThevenet commented on lasy/profiles/transverse/laguerre_gaussian_profile.py
> +        i.e. :math:`w_{0}` in the above formula.=
```suggestion
        i.e. :math:`w_{0}` in the above formula.
```

2024-11-26 19:14 UTC, MaxThevenet commented on lasy/profiles/transverse/laguerre_gaussian_profile.py
> +        i.e. :math:`m` in the above formula
```suggestion
        The order of Hermite polynomial in the x direction
        i.e. :math:`m` in the above formula.
```

2024-11-26 19:14 UTC, MaxThevenet commented on lasy/profiles/transverse/laguerre_gaussian_profile.py
> +        i.e. :math:`n` in the above formula
```suggestion
        The order of Hermite polynomial in the y direction
        i.e. :math:`n` in the above formula.
```

2024-11-26 19:14 UTC, MaxThevenet commented on lasy/profiles/transverse/laguerre_gaussian_profile.py
> +        z_eval = -z_foc  # this links our observation position to Siegmann's definition
```suggestion
        z_eval = -z_foc  # this links our observation position to Siegman's definition
```

2024-11-29 10:38 UTC, MaxThevenet approved these changes
Looks great, thanks!

2024-11-29 10:38 UTC, merged