Modify mode decomposition to gain independent value of waist in x and y dimension
LASY-org/lasy pull request #341
Opened 2024-12-28 18:26 UTC by Paaaaarth

2025-01-14 14:41 UTC, MaxThevenet requested changes
Thanks for this PR! See mostly one comment below.

2025-01-14 14:41 UTC, MaxThevenet commented on docs/source/tutorials/denoised_laser.ipynb
> +   "version": "3.11.4"
```suggestion
   "version": "3.12.2"
```

2025-01-14 14:41 UTC, MaxThevenet commented on lasy/utils/mode_decomposition.py
> +        The calculated waist in x and y axis.
I don't think one array of 2 elements is really appropriate here, for a few reasons:
- this is not consistent with x and y, passed as 2 different input arguments, and this is true for a few other variables;
- line 154 is very confusing, as x and y are treated asymmetrically in `wTest, waistTestY[I]` for no good reason;
- What you return is actually not array, rather a list.

Could you return e.g. `w0x` and `w0y` instead?

2025-01-14 14:41 UTC, MaxThevenet commented on lasy/utils/mode_decomposition.py
> +        )
Here, x and y are not treated symmetrically, which is not justified.

2025-02-04 15:46 UTC, Paaaaarth commented on lasy/utils/mode_decomposition.py
> +        )
All the requested changes have been implemented:)

2025-02-04 15:47 UTC, Paaaaarth commented on lasy/utils/mode_decomposition.py
> +        The calculated waist in x and y axis.
All the requested changes have been implemented:)

2025-02-05 08:27 UTC, MaxThevenet commented on lasy/utils/mode_decomposition.py
> +    for i in range(0, 30):
```suggestion
    for i in range(30):
```

2025-02-05 08:30 UTC, MaxThevenet approved these changes

2025-02-05 08:47 UTC, merged